#ifndef COLOR_FADING_CONSTANTS_H
#define COLOR_FADING_CONSTANTS_H

#include "types.h"
#include "macros.h"

#if defined(TMC_3DS) || defined(PORT_NATIVE)
#include "port_gba_mem.h"
#define COLOR_DATA_BG_EWRAM ((u16*)GBA_RESOLVE(EWRAM_BASE + 0x35000))
#define COLOR_DATA_OBJ_EWRAM ((u16*)GBA_RESOLVE(EWRAM_BASE + 0x35200))
#define COLOR_DATA_BG_EWRAM2 ((u16*)GBA_RESOLVE(EWRAM_BASE + 0x35000 + PALRAM_SIZE))
#define COLOR_DATA_OBJ_EWRAM2 ((u16*)GBA_RESOLVE(EWRAM_BASE + 0x35200 + PALRAM_SIZE))
#define COLOR_DATA_BG_EWRAM3 ((u16*)GBA_RESOLVE(EWRAM_BASE + 0x35000 + 2 * PALRAM_SIZE))
#define COLOR_DATA_OBJ_EWRAM3 ((u16*)GBA_RESOLVE(EWRAM_BASE + 0x35200 + 2 * PALRAM_SIZE))
#else
#define COLOR_DATA_BG_EWRAM ((u16*)(EWRAM_BASE + 0x35000))
#define COLOR_DATA_OBJ_EWRAM ((u16*)(EWRAM_BASE + 0x35200))
#define COLOR_DATA_BG_EWRAM2 ((u16*)(EWRAM_BASE + 0x35000 + PALRAM_SIZE))
#define COLOR_DATA_OBJ_EWRAM2 ((u16*)(EWRAM_BASE + 0x35200 + PALRAM_SIZE))
#define COLOR_DATA_BG_EWRAM3 ((u16*)(EWRAM_BASE + 0x35000 + 2 * PALRAM_SIZE))
#define COLOR_DATA_OBJ_EWRAM3 ((u16*)(EWRAM_BASE + 0x35200 + 2 * PALRAM_SIZE))
#endif


MAKE_ENUM(u8, EffectCutscene) {
    EFFECT_CUTSCENE_NONE,
    EFFECT_CUTSCENE_ESCAPING_CHOZODIA,
    EFFECT_CUTSCENE_ESCAPE_FAILED,
    EFFECT_CUTSCENE_EXITING_ZEBES,
    EFFECT_CUTSCENE_GETTING_FULLY_POWERED,
    EFFECT_CUTSCENE_RIDLEY_SPAWN,
    EFFECT_CUTSCENE_STATUE_OPENING,
    EFFECT_CUTSCENE_INTRO_TEXT,
    EFFECT_CUTSCENE_SAMUS_IN_BLUE_SHIP
};

MAKE_ENUM(u8, ColorFadingEffect) {
    COLOR_FADING_NONE,
    COLOR_FADING_FLASH,
    COLOR_FADING_CANCEL,
    COLOR_FADING_WHITE,
    COLOR_FADING_DOOR_TRANSITION,
    COLOR_FADING_FLASH2,
    COLOR_FADING_NO_TRANSITION,
    COLOR_FADING_FLASH_NO_TRANSITION,
    COLOR_FADING_NO_TRANSITION_HUD_HIDE,
    COLOR_FADING_SLOW_WHITE,
    COLOR_FADING_SLOW_BLACK,
    COLOR_FADING_AFTER_ENTER_MOTHER_SHIP,
    COLOR_FADING_ESCAPE_FAILED,
    COLOR_FADING_DEMO_ENDING_AUTO,
    COLOR_FADING_DEMO_ENDING_WITH_INPUT,
    COLOR_FADING_CHOZODIA_ESCAPE,
    COLOR_FADING_TOURIAN_ESCAPE,
    COLOR_FADING_GETTING_FULLY_POWERED,
    COLOR_FADING_RIDLEY_SPAWN,
    COLOR_FADING_STATUE_CUTSCENE,
    COLOR_FADING_INTRO_TEXT,
    COLOR_FADING_LANDING_SHIP,
    COLOR_FADING_SAMUS_IN_BLUE_SHIP,
    COLOR_FADING_TO_WHITE,
    COLOR_FADING_TO_BLACK,

    COLOR_FADING_COUNT
};

MAKE_ENUM(u8, ColorFadingType) {
    COLOR_FADING_TYPE_IN,
    COLOR_FADING_TYPE_FLASH,
    COLOR_FADING_TYPE_OUT,
    COLOR_FADING_TYPE_UNK
};

MAKE_ENUM(u8, ColorFadingStage) {
    COLOR_FADING_STAGE_STARTED,
    COLOR_FADING_STAGE_IN_PROGRESS,
    COLOR_FADING_STAGE_FINISHED,
    COLOR_FADING_STAGE_AFTER_FINISHED
};

// todo: Speed or Length? Ex. Slow vs Long
MAKE_ENUM(u8, ColorFadingSpeed) {
    COLOR_FADING_SPEED_FASTER,
    COLOR_FADING_SPEED_FAST,
    COLOR_FADING_SPEED_NORMAL,
    COLOR_FADING_SPEED_SLOW,
    COLOR_FADING_SPEED_INSTANT,

    COLOR_FADING_SPEED_COUNT
};

// todo: Naming
MAKE_ENUM(u8, ColorFadingFunction) {
    COLOR_FADING_FUNCTION_EMPTY,
    COLOR_FADING_FUNCTION_1,
    COLOR_FADING_FUNCTION_2,
    COLOR_FADING_FUNCTION_3,

    COLOR_FADING_FUNCTION_COUNT
};

MAKE_ENUM(u8, MonochromeFading) {
    MONOCHROME_FADING_NONE,
    MONOCHROME_FADING_BLACK,
    MONOCHROME_FADING_WHITE,

    MONOCHROME_FADING_ACTIVE = 1 << 7,
    MONOCHROME_FADING_ENDED = UCHAR_MAX
};

MAKE_ENUM(u8, ColorFadingStatus) ENUM_FLAG {
    COLOR_FADING_STATUS_ON_BG =  1 << 0,
    COLOR_FADING_STATUS_ON_OBJ = 1 << 1
};

#endif /* COLOR_FADING_CONSTANTS_H */
