/* GENERATED by tools/gen_ra_iwram_map.py -- do not edit by hand.
 *
 * Maps a RetroAchievements IWRAM address (GBA 0x03000000 + offset) onto
 * the decomp global that lives there, so rcheevos reads the same bytes the
 * achievement author was looking at.  The generator explains how the GBA
 * layout is reconstructed and how it is checked; regenerate with:
 *
 *     DEVKITARM=/opt/devkitpro/devkitARM python3 tools/gen_ra_iwram_map.py
 *
 * Agrees with 110 RetroAchievements code notes as of generation.
 */

#include "port_ra_iwram_map.h"

extern unsigned char gDebugMode[];
extern unsigned char gBootDebugActive[];
extern unsigned char gFrameCounter16Bit[];
extern unsigned char gStereoFlag[];
extern unsigned char gSubGameModeStage[];
extern unsigned char gWrittenToBldalpha[];
extern unsigned char gWrittenToBldcnt_Internal[];
extern unsigned char gWrittenToDispcnt[];
extern unsigned char gUnk_300000C[];
extern unsigned char gWrittenToWinIn_H[];
extern unsigned char gWrittenToWinOut_L[];
extern unsigned char gBackdropColor[];
extern unsigned char gWrittenToBldy[];
extern unsigned char gFileScreenOptionsUnlocked[];
extern unsigned char gLanguage[];
extern unsigned char gGameCompletion[];
extern unsigned char gCompletedGameFlagCopy[];
extern unsigned char gMonochromeBgFading[];
extern unsigned char gWhichBgPositionIsWrittenToBG3OFS[];
extern unsigned char gSamusOnTopOfBackgrounds[];
extern unsigned char gDifficulty[];
extern unsigned char gUseMotherShipDoors[];
extern unsigned char gTimeAttackFlag[];
extern unsigned char gCutsceneToSkip[];
extern unsigned char gMusicTrackInfo[];
extern unsigned char gCurrentDemo[];
extern unsigned char gResetGame[];
extern unsigned char gDisableScrolling[];
extern unsigned char gSlowScrollingTimer[];
extern unsigned char gDisableMusic[];
extern unsigned char gDisableCutscenes_Unused[];
extern unsigned char gSkipDoorTransition[];
extern unsigned char gDisableSoftReset[];
extern unsigned char gCollectingTank[];
extern unsigned char gDisableAnimatedGraphicsTimer[];
extern unsigned char gAnimatedGraphicsToUpdate[];
extern unsigned char gDisableDoorAndTanks[];
extern unsigned char gDisablePause[];
extern unsigned char gHideHud[];
extern unsigned char gShipLandingFlag[];
extern unsigned char gDisableClipdataChangingTransparency[];
extern unsigned char gDisableAnimatedPalette[];
extern unsigned char gInGameCutscenesTriggered[];
extern unsigned char gCurrentArea[];
extern unsigned char gCurrentRoom[];
extern unsigned char gLastDoorUsed[];
extern unsigned char gLastDoorProperties[];
extern unsigned char gDisplayLocationText[];
extern unsigned char gMinimapX[];
extern unsigned char gMinimapY[];
extern unsigned char gNumberOfNeverReformBlocks[];
extern unsigned char gNumberOfItemsCollected[];
extern unsigned char gCurrentHazeValue[];
extern unsigned char gEffectYPosition[];
extern unsigned char gEffectYPositionOffset[];
extern unsigned char gUnk_3000070[];
extern unsigned char gScreenShakeXOffset[];
extern unsigned char gScreenShakeYOffset[];
extern unsigned char gScreenShakeRelated[];
extern unsigned char gDispcntBackup[];
extern unsigned char gSpriteset[];
extern unsigned char gCurrentClipdataAffectingAction[];
extern unsigned char gSpritesetEntryUsed[];
extern unsigned char gDoorUnlockTimer[];
extern unsigned char gDisableDrawingSprites[];
extern unsigned char gCurrentCutscene[];
extern unsigned char gTourianEscapeCutsceneStage[];
extern unsigned char gNoClipLockCamera[];
extern unsigned char gHazeInfo[];
extern unsigned char gIoRegistersBackup[];
extern unsigned char gBgPointersAndDimensions[];
extern unsigned char gCurrentRoomEntry[];
extern unsigned char gCurrentAffectingClipdata[];
extern unsigned char gUnk_30000E0[];
extern unsigned char gBackgroundPositions[];
extern unsigned char gWaitingSpacePiratesPosition[];
extern unsigned char gBg2Movement[];
extern unsigned char gLockScreen[];
extern unsigned char gSuitFlashEffect[];
extern unsigned char gScreenShakeY[];
extern unsigned char gScreenShakeX[];
extern unsigned char gCurrentScrolls[];
extern unsigned char gCurrentPowerBomb[];
extern unsigned char gCamera[];
extern unsigned char gMaxInGameTimerFlag[];
extern unsigned char gInGameTimer[];
extern unsigned char gBestCompletionTimes[];
extern unsigned char gInGameTimerAtBosses[];
extern unsigned char gLastElevatorUsed[];
extern unsigned char gInGameCutscene[];
extern unsigned char gAlarmTimer[];
extern unsigned char gSpriteData[];
extern unsigned char gSpritesetSpritesId[];
extern unsigned char gSpritesetGfxSlots[];
extern unsigned char gSubSpriteData1[];
extern unsigned char gSubSpriteData2[];
extern unsigned char gParasiteRelated[];
extern unsigned char gCurrentSprite[];
extern unsigned char gSpriteDebris[];
extern unsigned char gPreviousVerticalCollisionCheck[];
extern unsigned char gPreviousCollisionCheck[];
extern unsigned char gIgnoreSamusAndSpriteCollision[];
extern unsigned char gSpriteDrawOrder[];
extern unsigned char gBossWork[];
extern unsigned char gSpriteRng[];
extern unsigned char gParticleEffects[];
extern unsigned char gMissileHighlightStatus[];
extern unsigned char gPowerBombHighlightStatus[];
extern unsigned char gSuperMissileHighlightStatus[];
extern unsigned char gUpdateMinimapFlag[];
extern unsigned char gEnergyDigits[];
extern unsigned char gMaxEnergyDigits[];
extern unsigned char gMissileDigits[];
extern unsigned char gPowerBombDigits[];
extern unsigned char gSuperMissileDigits[];
extern unsigned char gCurrentParticleEffectOamFramePointer[];
extern unsigned char gAmmoDigitsGfx[];
extern unsigned char gCurrentEscapeStatus[];
extern unsigned char gEscapeTimerCounter[];
extern unsigned char gEscapeTimerDigits[];
extern unsigned char gParticleEscapeOamFrames[];
extern unsigned char gEnergyRefillAnimation[];
extern unsigned char gMissileRefillAnimation[];
extern unsigned char gSuperMissileRefillAnimation[];
extern unsigned char gPowerBombRefillAnimation[];
extern unsigned char gParticleSamusReflectionOamFrames[];
extern unsigned char gProjectileData[];
extern unsigned char gArmCannonY[];
extern unsigned char gArmCannonX[];
extern unsigned char gPauseScreenFlag[];
extern unsigned char gAreaBeforeTransition[];
extern unsigned char gCurrentItemBeingAcquired[];
extern unsigned char gOptionsOptionSelected[];
extern unsigned char gBg0HOFS_NonGameplay[];
extern unsigned char gBg0VOFS_NonGameplay[];
extern unsigned char gBg1HOFS_NonGameplay[];
extern unsigned char gBg1VOFS_NonGameplay[];
extern unsigned char gBg2HOFS_NonGameplay[];
extern unsigned char gBg2VOFS_NonGameplay[];
extern unsigned char gBg3HOFS_NonGameplay[];
extern unsigned char gBg3VOFS_NonGameplay[];
extern unsigned char gCurrentOamRotation[];
extern unsigned char gCurrentOamScaling[];
extern unsigned char gLastAreaNameVisited[];
extern unsigned char gCurrentMessage[];
extern unsigned char gSramCorruptFlag[];
extern unsigned char gIsLoadingFile[];
extern unsigned char gMostRecentSaveFile[];
extern unsigned char gHasSaved[];
extern unsigned char gUnk_3000C20[];
extern unsigned char gSramOperationStage[];
extern unsigned char gSaveFilesInfo[];
extern unsigned char gSectionInfo[];
extern unsigned char gMainGameMode[];
extern unsigned char gSubGameMode1[];
extern unsigned char gSubGameMode2[];
extern unsigned char gSubGameMode3[];
extern unsigned char gVblankActive[];
extern unsigned char gFrameCounter8Bit[];
extern unsigned char gVBlankRequestFlag[];
extern unsigned char gUnk_3000C7A[];
extern unsigned char gInterruptCode[];
extern unsigned char gOamData[];
extern unsigned char gButtonInput[];
extern unsigned char gPreviousButtonInput[];
extern unsigned char gChangedInput[];
extern unsigned char gNextOamSlot[];
extern unsigned char gUnk_3001383[];
extern unsigned char gWrittenToBg2X[];
extern unsigned char gWrittenToBg2Y[];
extern unsigned char gWrittenToMosaic_H[];
extern unsigned char gWrittenToMosaic_L[];
extern unsigned char gBg2XScaling[];
extern unsigned char gBg2YScaling[];
extern unsigned char gBg2Rotation[];
extern unsigned char gWrittenToBg2Pa[];
extern unsigned char gWrittenToBg2Pb[];
extern unsigned char gWrittenToBg2Pc[];
extern unsigned char gWrittenToBg2Pd[];
extern unsigned char gWrittenToBldy_NonGameplay[];
extern unsigned char gWrittenToBldalpha_L[];
extern unsigned char gWrittenToBldalpha_H[];
extern unsigned char gBg0XPosition[];
extern unsigned char gBg0YPosition[];
extern unsigned char gBg1XPosition[];
extern unsigned char gBg1YPosition[];
extern unsigned char gBg2XPosition[];
extern unsigned char gBg2YPosition[];
extern unsigned char gBg3XPosition[];
extern unsigned char gBg3YPosition[];
extern unsigned char gUnk_30013C3[];
extern unsigned char gDemoState[];
extern unsigned char gSamusData[];
extern unsigned char gSamusDataCopy[];
extern unsigned char gSamusWeaponInfo[];
extern unsigned char gSamusEcho[];
extern unsigned char gScrewSpeedAnimation[];
extern unsigned char gEquipment[];
extern unsigned char gSamusHazardDamage[];
extern unsigned char gSamusEnvironmentalEffects[];
extern unsigned char gSamusPhysics[];
extern unsigned char gPreviousXPosition[];
extern unsigned char gPreviousYPosition[];
extern unsigned char gEndingFlags[];
extern unsigned char gPreventMovementTimer[];
extern unsigned char gDisableDrawingSamusAndScrolling[];
extern unsigned char gTimeAttackData[];
extern unsigned char gUnk_3001670[];
extern unsigned char gButtonAssignments[];
extern unsigned char gTimeAttackRecord[];
extern unsigned char gNonGameplayRam[];
extern unsigned char gVBlankCallback[];
extern unsigned char gHBlankCallback[];
extern unsigned char gVCountCallback[];
extern unsigned char gSerialCommunicationCallback[];
extern unsigned char gTimer3Callback[];
extern unsigned char gMusicInfo[];
extern unsigned char gUnk_3003760[];
extern unsigned char gUnk_300376C[];
extern unsigned char gPsgSounds[];
extern unsigned char gSoundChannelBackup[];
extern unsigned char gSoundChannelTrack2Backup[];
extern unsigned char gSoundQueue[];
extern unsigned char gSoundCodeAPointer[];
extern unsigned char gSoundCodeA[];
extern unsigned char gSoundCodeBPointer[];
extern unsigned char gSoundCodeB[];
extern unsigned char gSoundCodeCPointer[];
extern unsigned char gSoundCodeC[];
extern unsigned char gUnk_3004344[];
extern unsigned char gTrack0Variables[];
extern unsigned char gTrack1Variables[];
extern unsigned char gTrack2Variables[];
extern unsigned char gTrack3Variables[];
extern unsigned char gTrack4Variables[];
extern unsigned char gTrack5Variables[];
extern unsigned char gTrack6Variables[];
extern unsigned char gTrack7Variables[];
extern unsigned char gTrack8Variables[];
extern unsigned char gUnk_3004FC8[];
extern unsigned char gUnk_03004FC9[];
extern unsigned char gDemoInputData[];
extern unsigned char gDemoInputDuration[];
extern unsigned char gDemoInputNumber[];
extern unsigned char gDemoInputTimer[];
extern unsigned char gDemoInput[];
extern unsigned char gNotPressingUp[];
extern unsigned char gDebugVCount_InGameStart[];
extern unsigned char gDebugVCount_InGameEnd[];
extern unsigned char gDebugVCount_VBlankEnd[];
extern unsigned char gDebugVCount_AudioMax[];
extern unsigned char gUnk_30053DA[];
extern unsigned char gSamusPalette[];
extern unsigned char gSamusPaletteSize[];
extern unsigned char gUnk_3005442[];
extern unsigned char gWrittenToWin1H[];
extern unsigned char gWrittenToWin1V[];
extern unsigned char gWrittenToBldcnt[];
extern unsigned char gTilemapAndClipPointers[];
extern unsigned char gHatchData[];
extern unsigned char gNumberOfValidHatchesInRoom[];
extern unsigned char gDoorPositionStart[];
extern unsigned char gHatchesState[];
extern unsigned char gBg3Movement[];
extern unsigned char gBg0Movement[];
extern unsigned char gTilesetTransparentColor[];
extern unsigned char gUnk_3005500[];
extern unsigned char gUnusedStruct_3005504[];
extern unsigned char gSamusDoorPositionOffset[];
extern unsigned char gDestinationRoom[];
extern unsigned char gBg3CntDuringDoorTransition[];
extern unsigned char gBg1CntDuringDoorTransition[];
extern unsigned char gUnk_3005514[];
extern unsigned char gScreenYOffset[];
extern unsigned char gScreenXOffset[];
extern unsigned char gRainSoundEffect[];
extern unsigned char gWaterMovement[];
extern unsigned char gColorFading[];
extern unsigned char gBrokenBlocks[];
extern unsigned char gLastTankCollected[];
extern unsigned char gBombChains[];
extern unsigned char gActiveBombChainTypes[];
extern unsigned char gTransparencyRelated[];
extern unsigned char gDefaultTransparency[];
extern unsigned char gBldalphaData1[];
extern unsigned char gBldalphaData2[];
extern unsigned char gBldyData1[];
extern unsigned char gBldyData2[];
extern unsigned char gAnimatedPaletteTiming[];
extern unsigned char gHatchFlashingAnimation[];
extern unsigned char gAnimatedGraphicsEntry[];
extern unsigned char gBackgroundEffect[];
extern unsigned char gScrollCounter[];
extern unsigned char gClipdataCodePointer[];
extern unsigned char gCurrentRoomScrollDataPointer[];
extern unsigned char gUnk_300570C[];
extern unsigned char gScrollingVelocityCaps[];
extern unsigned char gHazeLoops[];
extern unsigned char gUnk_3005728[];
extern unsigned char gUnk_3005729[];
extern unsigned char gHazeProcessCodePointer[];
extern unsigned char gAnimatedGraphicsData[];
extern unsigned char gTankAnimations[];
extern unsigned char gMaintainedInputData[];
extern unsigned char gPrevChangedInput[];
extern unsigned char gOamXOffset_NonGameplay[];
extern unsigned char gOamYOffset_NonGameplay[];
extern unsigned char gIoTransferInfo[];
extern unsigned char gMultiBootParamData[];
extern unsigned char gDataSentPointer[];
extern unsigned char gDataSentSize[];
extern unsigned char gMultibootErrorFlags[];
extern unsigned char gUnk_3005878[];
extern unsigned char gMultibootUnk_3005880[];
extern unsigned char gMultibootInProgress[];
extern unsigned char gUnk_3005886[];
extern unsigned char gMultiBootRequiredData[];
extern unsigned char gTransferManager[];
extern unsigned char gTransferUpdateResult[];
extern unsigned char gTransferUnk_30058aa[];
extern unsigned char gTransferDataTimer[];
extern unsigned char gTransferStartupTimer[];
extern unsigned char gTransferUnk_30058af[];
extern unsigned char gTransferGbaDetectedCount[];
extern unsigned char gTransferGbaId[];
extern unsigned char gRegIme_Backup[];
extern unsigned char gRegIe_Backup[];
extern unsigned char gRegTm3Cnt_H_Backup[];
extern unsigned char gRegSiocnt_Backup[];
extern unsigned char gRegRcnt_Backup[];
extern unsigned char gLinkStatus[];
extern unsigned char gSendCmd[];
extern unsigned char gRecvCmds[];
extern unsigned char gShouldAdvanceLinkState[];
extern unsigned char gLinkPlayerCount[];
extern unsigned char gLinkLocalId[];
extern unsigned char gLinkUnkFlag9[];
extern unsigned char gLinkSavedIme[];
extern unsigned char gNumVBlanksWithoutSerialIntr[];
extern unsigned char gSendBufferEmpty[];
extern unsigned char gUnk_000058D4[];
extern unsigned char gHandshakePlayerCount[];
extern unsigned char gChecksumAvailable[];
extern unsigned char gSendNonzeroCheck[];
extern unsigned char gRecvNonzeroCheck[];
extern unsigned char gUnk_3005908[];
extern unsigned char gTrackData8[];
extern unsigned char gTrackData3[];
extern unsigned char gTrackData1[];
extern unsigned char gTrackData6[];
extern unsigned char gTrackData4[];
extern unsigned char gTrackData0[];
extern unsigned char gTrackData7[];
extern unsigned char gTrackData2[];
extern unsigned char gTrackData5[];
extern unsigned char gLastSendQueueCount[];
extern unsigned char gUnk_3005B51[];
extern unsigned char gLastRecvQueueCount[];
extern unsigned char gUnk_3005B55[];
extern unsigned char gLink[];

/* Sorted by address, so a lookup can binary-search it. */
const PortRaIwramEntry gPortRaIwramMap[] = {
    { 0x0000, 1, gDebugMode },
    { 0x0001, 1, gBootDebugActive },
    { 0x0002, 2, gFrameCounter16Bit },
    { 0x0004, 1, gStereoFlag },
    { 0x0005, 1, gSubGameModeStage },
    { 0x0006, 2, gWrittenToBldalpha },
    { 0x0008, 2, gWrittenToBldcnt_Internal },
    { 0x000a, 2, gWrittenToDispcnt },
    { 0x000c, 2, gUnk_300000C },
    { 0x000e, 1, gWrittenToWinIn_H },
    { 0x000f, 1, gWrittenToWinOut_L },
    { 0x0010, 2, gBackdropColor },
    { 0x0012, 1, gWrittenToBldy },
    { 0x0014, 12, gFileScreenOptionsUnlocked },
    { 0x0020, 1, gLanguage },
    { 0x0024, 3, gGameCompletion },
    { 0x0027, 1, gCompletedGameFlagCopy },
    { 0x0028, 1, gMonochromeBgFading },
    { 0x0029, 1, gWhichBgPositionIsWrittenToBG3OFS },
    { 0x002a, 1, gSamusOnTopOfBackgrounds },
    { 0x002c, 1, gDifficulty },
    { 0x002d, 1, gUseMotherShipDoors },
    { 0x002e, 1, gTimeAttackFlag },
    { 0x002f, 1, gCutsceneToSkip },
    { 0x0030, 6, gMusicTrackInfo },
    { 0x0038, 4, gCurrentDemo },
    { 0x003c, 1, gResetGame },
    { 0x003d, 1, gDisableScrolling },
    { 0x003e, 2, gSlowScrollingTimer },
    { 0x0040, 1, gDisableMusic },
    { 0x0041, 1, gDisableCutscenes_Unused },
    { 0x0042, 1, gSkipDoorTransition },
    { 0x0043, 1, gDisableSoftReset },
    { 0x0044, 1, gCollectingTank },
    { 0x0045, 1, gDisableAnimatedGraphicsTimer },
    { 0x0046, 2, gAnimatedGraphicsToUpdate },
    { 0x0048, 1, gDisableDoorAndTanks },
    { 0x0049, 1, gDisablePause },
    { 0x004a, 1, gHideHud },
    { 0x004b, 1, gShipLandingFlag },
    { 0x004c, 1, gDisableClipdataChangingTransparency },
    { 0x004d, 1, gDisableAnimatedPalette },
    { 0x0050, 4, gInGameCutscenesTriggered },
    { 0x0054, 1, gCurrentArea },
    { 0x0055, 1, gCurrentRoom },
    { 0x0056, 1, gLastDoorUsed },
    { 0x0057, 1, gLastDoorProperties },
    { 0x0058, 1, gDisplayLocationText },
    { 0x0059, 1, gMinimapX },
    { 0x005a, 1, gMinimapY },
    { 0x005b, 8, gNumberOfNeverReformBlocks },
    { 0x0063, 8, gNumberOfItemsCollected },
    { 0x006c, 1, gCurrentHazeValue },
    { 0x006e, 2, gEffectYPosition },
    { 0x0070, 2, gEffectYPositionOffset },
    { 0x0072, 1, gUnk_3000070 },
    { 0x0073, 1, gScreenShakeXOffset },
    { 0x0074, 1, gScreenShakeYOffset },
    { 0x0076, 2, gScreenShakeRelated },
    { 0x0078, 2, gDispcntBackup },
    { 0x007a, 1, gSpriteset },
    { 0x007b, 1, gCurrentClipdataAffectingAction },
    { 0x007c, 1, gSpritesetEntryUsed },
    { 0x007d, 1, gDoorUnlockTimer },
    { 0x007e, 1, gDisableDrawingSprites },
    { 0x007f, 1, gCurrentCutscene },
    { 0x0080, 1, gTourianEscapeCutsceneStage },
    { 0x0081, 1, gNoClipLockCamera },
    { 0x0084, 8, gHazeInfo },
    { 0x008c, 20, gIoRegistersBackup },
    { 0x00a0, 32, gBgPointersAndDimensions },
    { 0x00c0, 32, gCurrentRoomEntry },
    { 0x00e0, 4, gCurrentAffectingClipdata },
    { 0x00e4, 4, gUnk_30000E0 },
    { 0x00e8, 20, gBackgroundPositions },
    { 0x00fc, 4, gWaitingSpacePiratesPosition },
    { 0x0100, 4, gBg2Movement },
    { 0x0104, 6, gLockScreen },
    { 0x010c, 5, gSuitFlashEffect },
    { 0x0114, 4, gScreenShakeY },
    { 0x0118, 4, gScreenShakeX },
    { 0x011c, 20, gCurrentScrolls },
    { 0x0130, 20, gCurrentPowerBomb },
    { 0x0144, 6, gCamera },
    { 0x014a, 1, gMaxInGameTimerFlag },
    { 0x014c, 4, gInGameTimer },
    { 0x0150, 48, gBestCompletionTimes },
    { 0x0180, 20, gInGameTimerAtBosses },
    { 0x0194, 4, gLastElevatorUsed },
    { 0x0198, 12, gInGameCutscene },
    { 0x01a4, 2, gAlarmTimer },
    { 0x01a8, 1344, gSpriteData },
    { 0x06e8, 15, gSpritesetSpritesId },
    { 0x06f8, 15, gSpritesetGfxSlots },
    { 0x0708, 20, gSubSpriteData1 },
    { 0x071c, 20, gSubSpriteData2 },
    { 0x0730, 1, gParasiteRelated },
    { 0x0734, 56, gCurrentSprite },
    { 0x076c, 128, gSpriteDebris },
    { 0x07ec, 1, gPreviousVerticalCollisionCheck },
    { 0x07ed, 1, gPreviousCollisionCheck },
    { 0x07ee, 1, gIgnoreSamusAndSpriteCollision },
    { 0x07f0, 24, gSpriteDrawOrder },
    { 0x0808, 48, gBossWork },
    { 0x0838, 1, gSpriteRng },
    { 0x083c, 192, gParticleEffects },
    { 0x08fc, 1, gMissileHighlightStatus },
    { 0x08fd, 1, gPowerBombHighlightStatus },
    { 0x08fe, 1, gSuperMissileHighlightStatus },
    { 0x08ff, 1, gUpdateMinimapFlag },
    { 0x0900, 4, gEnergyDigits },
    { 0x0904, 4, gMaxEnergyDigits },
    { 0x0908, 4, gMissileDigits },
    { 0x090c, 4, gPowerBombDigits },
    { 0x0910, 4, gSuperMissileDigits },
    { 0x0914, 4, gCurrentParticleEffectOamFramePointer },
    { 0x0918, 64, gAmmoDigitsGfx },
    { 0x095c, 1, gCurrentEscapeStatus },
    { 0x095d, 1, gEscapeTimerCounter },
    { 0x095e, 6, gEscapeTimerDigits },
    { 0x0964, 50, gParticleEscapeOamFrames },
    { 0x0996, 1, gEnergyRefillAnimation },
    { 0x0997, 1, gMissileRefillAnimation },
    { 0x0998, 1, gSuperMissileRefillAnimation },
    { 0x0999, 1, gPowerBombRefillAnimation },
    { 0x099c, 146, gParticleSamusReflectionOamFrames },
    { 0x0a30, 448, gProjectileData },
    { 0x0bf0, 2, gArmCannonY },
    { 0x0bf2, 2, gArmCannonX },
    { 0x0bf4, 1, gPauseScreenFlag },
    { 0x0bf5, 1, gAreaBeforeTransition },
    { 0x0bf6, 1, gCurrentItemBeingAcquired },
    { 0x0bf7, 1, gOptionsOptionSelected },
    { 0x0bf8, 2, gBg0HOFS_NonGameplay },
    { 0x0bfa, 2, gBg0VOFS_NonGameplay },
    { 0x0bfc, 2, gBg1HOFS_NonGameplay },
    { 0x0bfe, 2, gBg1VOFS_NonGameplay },
    { 0x0c00, 2, gBg2HOFS_NonGameplay },
    { 0x0c02, 2, gBg2VOFS_NonGameplay },
    { 0x0c04, 2, gBg3HOFS_NonGameplay },
    { 0x0c06, 2, gBg3VOFS_NonGameplay },
    { 0x0c08, 2, gCurrentOamRotation },
    { 0x0c0a, 2, gCurrentOamScaling },
    { 0x0c0c, 4, gLastAreaNameVisited },
    { 0x0c10, 16, gCurrentMessage },
    { 0x0c20, 1, gSramCorruptFlag },
    { 0x0c21, 1, gIsLoadingFile },
    { 0x0c22, 1, gMostRecentSaveFile },
    { 0x0c23, 1, gHasSaved },
    { 0x0c24, 1, gUnk_3000C20 },
    { 0x0c25, 1, gSramOperationStage },
    { 0x0c28, 66, gSaveFilesInfo },
    { 0x0c6c, 4, gSectionInfo },
    { 0x0c70, 2, gMainGameMode },
    { 0x0c72, 2, gSubGameMode1 },
    { 0x0c74, 1, gSubGameMode2 },
    { 0x0c75, 1, gSubGameMode3 },
    { 0x0c76, 1, gVblankActive },
    { 0x0c77, 1, gFrameCounter8Bit },
    { 0x0c78, 2, gVBlankRequestFlag },
    { 0x0c7a, 1, gUnk_3000C7A },
    { 0x0c7c, 512, gInterruptCode },
    { 0x0e7c, 1280, gOamData },
    { 0x137c, 2, gButtonInput },
    { 0x137e, 2, gPreviousButtonInput },
    { 0x1380, 2, gChangedInput },
    { 0x1382, 1, gNextOamSlot },
    { 0x1384, 17, gUnk_3001383 },
    { 0x1395, 4, gWrittenToBg2X },
    { 0x1399, 4, gWrittenToBg2Y },
    { 0x139d, 2, gWrittenToMosaic_H },
    { 0x139f, 2, gWrittenToMosaic_L },
    { 0x13a1, 2, gBg2XScaling },
    { 0x13a3, 2, gBg2YScaling },
    { 0x13a5, 2, gBg2Rotation },
    { 0x13a7, 2, gWrittenToBg2Pa },
    { 0x13a9, 2, gWrittenToBg2Pb },
    { 0x13ab, 2, gWrittenToBg2Pc },
    { 0x13ad, 2, gWrittenToBg2Pd },
    { 0x13af, 2, gWrittenToBldy_NonGameplay },
    { 0x13b1, 2, gWrittenToBldalpha_L },
    { 0x13b3, 2, gWrittenToBldalpha_H },
    { 0x13b5, 2, gBg0XPosition },
    { 0x13b7, 2, gBg0YPosition },
    { 0x13b9, 2, gBg1XPosition },
    { 0x13bb, 2, gBg1YPosition },
    { 0x13bd, 2, gBg2XPosition },
    { 0x13bf, 2, gBg2YPosition },
    { 0x13c1, 2, gBg3XPosition },
    { 0x13c3, 2, gBg3YPosition },
    { 0x13c5, 14, gUnk_30013C3 },
    { 0x13d3, 1, gDemoState },
    { 0x13d4, 30, gSamusData },
    { 0x13f4, 30, gSamusDataCopy },
    { 0x1418, 4, gSamusWeaponInfo },
    { 0x141c, 268, gSamusEcho },
    { 0x1528, 8, gScrewSpeedAnimation },
    { 0x1530, 20, gEquipment },
    { 0x1548, 6, gSamusHazardDamage },
    { 0x1550, 60, gSamusEnvironmentalEffects },
    { 0x158c, 120, gSamusPhysics },
    { 0x1604, 2, gPreviousXPosition },
    { 0x1606, 2, gPreviousYPosition },
    { 0x1608, 1, gEndingFlags },
    { 0x160a, 2, gPreventMovementTimer },
    { 0x160c, 1, gDisableDrawingSamusAndScrolling },
    { 0x1610, 100, gTimeAttackData },
    { 0x1674, 28, gUnk_3001670 },
    { 0x1690, 8, gButtonAssignments },
    { 0x1698, 48, gTimeAttackRecord },
    { 0x16c8, 1576, gNonGameplayRam },
    { 0x1cf0, 4, gVBlankCallback },
    { 0x1cf4, 4, gHBlankCallback },
    { 0x1cf8, 4, gVCountCallback },
    { 0x1cfc, 4, gSerialCommunicationCallback },
    { 0x1d00, 4, gTimer3Callback },
    { 0x1d04, 6752, gMusicInfo },
    { 0x3764, 12, gUnk_3003760 },
    { 0x3770, 320, gUnk_300376C },
    { 0x38b0, 160, gPsgSounds },
    { 0x3950, 392, gSoundChannelBackup },
    { 0x3ad8, 392, gSoundChannelTrack2Backup },
    { 0x3c60, 72, gSoundQueue },
    { 0x3ca8, 4, gSoundCodeAPointer },
    { 0x3cac, 1624, gSoundCodeA },
    { 0x4304, 4, gSoundCodeBPointer },
    { 0x4308, 164, gSoundCodeB },
    { 0x43ac, 4, gSoundCodeCPointer },
    { 0x43b0, 176, gSoundCodeC },
    { 0x4460, 1, gUnk_3004344 },
    { 0x4464, 960, gTrack0Variables },
    { 0x4824, 800, gTrack1Variables },
    { 0x4b44, 160, gTrack2Variables },
    { 0x4be4, 160, gTrack3Variables },
    { 0x4c84, 160, gTrack4Variables },
    { 0x4d24, 160, gTrack5Variables },
    { 0x4dc4, 240, gTrack6Variables },
    { 0x4eb4, 80, gTrack7Variables },
    { 0x4f04, 480, gTrack8Variables },
    { 0x50e4, 1, gUnk_3004FC8 },
    { 0x50e5, 1, gUnk_03004FC9 },
    { 0x50e8, 512, gDemoInputData },
    { 0x52e8, 512, gDemoInputDuration },
    { 0x54e8, 2, gDemoInputNumber },
    { 0x54ea, 2, gDemoInputTimer },
    { 0x54ec, 2, gDemoInput },
    { 0x54ee, 1, gNotPressingUp },
    { 0x54f0, 2, gDebugVCount_InGameStart },
    { 0x54f2, 2, gDebugVCount_InGameEnd },
    { 0x54f4, 2, gDebugVCount_VBlankEnd },
    { 0x54f6, 2, gDebugVCount_AudioMax },
    { 0x54f8, 6, gUnk_30053DA },
    { 0x5500, 96, gSamusPalette },
    { 0x5560, 2, gSamusPaletteSize },
    { 0x5564, 6, gUnk_3005442 },
    { 0x556a, 2, gWrittenToWin1H },
    { 0x556c, 2, gWrittenToWin1V },
    { 0x556e, 2, gWrittenToBldcnt },
    { 0x5570, 12, gTilemapAndClipPointers },
    { 0x557c, 128, gHatchData },
    { 0x55fc, 1, gNumberOfValidHatchesInRoom },
    { 0x5600, 4, gDoorPositionStart },
    { 0x5604, 8, gHatchesState },
    { 0x560c, 6, gBg3Movement },
    { 0x5614, 8, gBg0Movement },
    { 0x561c, 4, gTilesetTransparentColor },
    { 0x5620, 4, gUnk_3005500 },
    { 0x5624, 8, gUnusedStruct_3005504 },
    { 0x562c, 2, gSamusDoorPositionOffset },
    { 0x562e, 1, gDestinationRoom },
    { 0x5630, 2, gBg3CntDuringDoorTransition },
    { 0x5632, 2, gBg1CntDuringDoorTransition },
    { 0x5634, 1, gUnk_3005514 },
    { 0x5635, 1, gScreenYOffset },
    { 0x5636, 2, gScreenXOffset },
    { 0x5638, 2, gRainSoundEffect },
    { 0x563c, 4, gWaterMovement },
    { 0x5640, 8, gColorFading },
    { 0x5648, 384, gBrokenBlocks },
    { 0x57c8, 4, gLastTankCollected },
    { 0x57cc, 16, gBombChains },
    { 0x57dc, 1, gActiveBombChainTypes },
    { 0x57e0, 4, gTransparencyRelated },
    { 0x57e4, 6, gDefaultTransparency },
    { 0x57ec, 8, gBldalphaData1 },
    { 0x57f4, 8, gBldalphaData2 },
    { 0x57fc, 8, gBldyData1 },
    { 0x5804, 8, gBldyData2 },
    { 0x580c, 4, gAnimatedPaletteTiming },
    { 0x5810, 4, gHatchFlashingAnimation },
    { 0x5814, 2, gAnimatedGraphicsEntry },
    { 0x5818, 8, gBackgroundEffect },
    { 0x5820, 1, gScrollCounter },
    { 0x5824, 4, gClipdataCodePointer },
    { 0x5828, 4, gCurrentRoomScrollDataPointer },
    { 0x582c, 8, gUnk_300570C },
    { 0x5834, 8, gScrollingVelocityCaps },
    { 0x583c, 12, gHazeLoops },
    { 0x5848, 1, gUnk_3005728 },
    { 0x5849, 1, gUnk_3005729 },
    { 0x584c, 4, gHazeProcessCodePointer },
    { 0x5850, 192, gAnimatedGraphicsData },
    { 0x5910, 12, gTankAnimations },
    { 0x591c, 2, gMaintainedInputData },
    { 0x591e, 2, gPrevChangedInput },
    { 0x5920, 1, gOamXOffset_NonGameplay },
    { 0x5921, 1, gOamYOffset_NonGameplay },
    { 0x5924, 24, gIoTransferInfo },
    { 0x593c, 76, gMultiBootParamData },
    { 0x5988, 4, gDataSentPointer },
    { 0x598c, 4, gDataSentSize },
    { 0x5990, 4, gMultibootErrorFlags },
    { 0x5994, 8, gUnk_3005878 },
    { 0x599c, 4, gMultibootUnk_3005880 },
    { 0x59a0, 1, gMultibootInProgress },
    { 0x59a4, 2, gUnk_3005886 },
    { 0x59a8, 6, gMultiBootRequiredData },
    { 0x59b0, 24, gTransferManager },
    { 0x59c8, 2, gTransferUpdateResult },
    { 0x59ca, 1, gTransferUnk_30058aa },
    { 0x59cc, 2, gTransferDataTimer },
    { 0x59ce, 1, gTransferStartupTimer },
    { 0x59cf, 1, gTransferUnk_30058af },
    { 0x59d0, 1, gTransferGbaDetectedCount },
    { 0x59d1, 1, gTransferGbaId },
    { 0x59d2, 2, gRegIme_Backup },
    { 0x59d4, 2, gRegIe_Backup },
    { 0x59d6, 2, gRegTm3Cnt_H_Backup },
    { 0x59d8, 2, gRegSiocnt_Backup },
    { 0x59da, 2, gRegRcnt_Backup },
    { 0x59dc, 4, gLinkStatus },
    { 0x59e0, 4, gSendCmd },
    { 0x59e4, 8, gRecvCmds },
    { 0x59ec, 1, gShouldAdvanceLinkState },
    { 0x59ed, 1, gLinkPlayerCount },
    { 0x59ee, 1, gLinkLocalId },
    { 0x59ef, 1, gLinkUnkFlag9 },
    { 0x59f0, 2, gLinkSavedIme },
    { 0x59f2, 1, gNumVBlanksWithoutSerialIntr },
    { 0x59f3, 1, gSendBufferEmpty },
    { 0x59f4, 1, gUnk_000058D4 },
    { 0x59f5, 1, gHandshakePlayerCount },
    { 0x59f6, 1, gChecksumAvailable },
    { 0x59f8, 2, gSendNonzeroCheck },
    { 0x59fa, 2, gRecvNonzeroCheck },
    { 0x59fc, 8, gUnk_3005908 },
    { 0x5a04, 64, gTrackData8 },
    { 0x5a44, 64, gTrackData3 },
    { 0x5a84, 64, gTrackData1 },
    { 0x5ac4, 64, gTrackData6 },
    { 0x5b04, 64, gTrackData4 },
    { 0x5b44, 64, gTrackData0 },
    { 0x5b84, 64, gTrackData7 },
    { 0x5bc4, 64, gTrackData2 },
    { 0x5c04, 64, gTrackData5 },
    { 0x5c44, 1, gLastSendQueueCount },
    { 0x5c48, 3, gUnk_3005B51 },
    { 0x5c4b, 1, gLastRecvQueueCount },
    { 0x5c4c, 11, gUnk_3005B55 },
    { 0x5c58, 412, gLink },
};

const unsigned int gPortRaIwramMapCount =
    (unsigned int)(sizeof(gPortRaIwramMap) / sizeof(gPortRaIwramMap[0]));
