#ifndef FILE_SELECT_CONSTANTS_H
#define FILE_SELECT_CONSTANTS_H

#include "types.h"
#include "macros.h"

MAKE_ENUM(u8, FileSelectSelectionSet) {
    FILE_SELECT_SELECTION_SET_ALL_FILES,
    FILE_SELECT_SELECTION_SET_ONLY_FILES,
    FILE_SELECT_SELECTION_SET_ALL_FILES_NO_COPY
};

MAKE_ENUM(u8, FileSelectFadingStage) {
    FILE_SELECT_FADING_STAGE_FADE_IN,
    FILE_SELECT_FADING_STAGE_CHECK_FADE_IN,
    FILE_SELECT_FADING_STAGE_FADE_OUT,
    FILE_SELECT_FADING_STAGE_CHECK_FADE_OUT
};

/*
 * EUR renders the file-screen message in ONE stage that loops over up to 8
 * lines; the other regions use four stages, one per line. The port has to
 * serve every region from one binary, so it needs both sets of values to
 * exist at once: LINE doubles as LINE_1, and UPDATE_QUEUE sits after LINE_4.
 * That moves UPDATE_QUEUE from 3 to 6 for EUR, which is why the EUR path in
 * FileScreenProcessText assigns it explicitly instead of incrementing (see
 * the MZM_3DS branch there).
 *
 * The GBA build keeps the original per-region numbering so `make check` still
 * matches; LINE / LINE_1 are aliased so the shared code compiles either way.
 */
#if defined(MZM_3DS) || defined(PORT_NATIVE)
MAKE_ENUM(u8, FileScreenProcessTextStage) {
    FILE_SCREEN_PROCESS_TEXT_STAGE_NONE,
    FILE_SCREEN_PROCESS_TEXT_STAGE_INIT,
    FILE_SCREEN_PROCESS_TEXT_STAGE_LINE,
    FILE_SCREEN_PROCESS_TEXT_STAGE_LINE_2,
    FILE_SCREEN_PROCESS_TEXT_STAGE_LINE_3,
    FILE_SCREEN_PROCESS_TEXT_STAGE_LINE_4,
    FILE_SCREEN_PROCESS_TEXT_STAGE_UPDATE_QUEUE
};
#define FILE_SCREEN_PROCESS_TEXT_STAGE_LINE_1 FILE_SCREEN_PROCESS_TEXT_STAGE_LINE
#else
MAKE_ENUM(u8, FileScreenProcessTextStage) {
    FILE_SCREEN_PROCESS_TEXT_STAGE_NONE,
    FILE_SCREEN_PROCESS_TEXT_STAGE_INIT,
#ifdef REGION_EU
    FILE_SCREEN_PROCESS_TEXT_STAGE_LINE,
#else // !REGION_EU
    FILE_SCREEN_PROCESS_TEXT_STAGE_LINE_1,
    FILE_SCREEN_PROCESS_TEXT_STAGE_LINE_2,
    FILE_SCREEN_PROCESS_TEXT_STAGE_LINE_3,
    FILE_SCREEN_PROCESS_TEXT_STAGE_LINE_4,
#endif // REGION_EU
    FILE_SCREEN_PROCESS_TEXT_STAGE_UPDATE_QUEUE
};
#ifndef REGION_EU
#define FILE_SCREEN_PROCESS_TEXT_STAGE_LINE FILE_SCREEN_PROCESS_TEXT_STAGE_LINE_1
#endif
#endif

MAKE_ENUM(u8, FileSelectEraseFileStage) {
    FILE_SELECT_ERASE_FILE_STAGE_INIT,
    FILE_SELECT_ERASE_FILE_STAGE_WAIT_FOR_CHOOSE,
    FILE_SELECT_ERASE_FILE_STAGE_UPDATE_CHOOSE,
    FILE_SELECT_ERASE_FILE_STAGE_WAIT_FOR_CONFIRM,
    FILE_SELECT_ERASE_FILE_STAGE_UPDATE_CONFIRM,
    FILE_SELECT_ERASE_FILE_STAGE_CANCEL_CONFIRM,
    FILE_SELECT_ERASE_FILE_STAGE_RESTART_CHOOSE,
    FILE_SELECT_ERASE_FILE_STAGE_ERASE_FILE,
    FILE_SELECT_ERASE_FILE_STAGE_BEGIN_EXIT,
    FILE_SELECT_ERASE_FILE_STAGE_WAIT_FOR_EXIT,
    FILE_SELECT_ERASE_FILE_STAGE_UPDATE_ERASED_FILE,
    FILE_SELECT_ERASE_FILE_STAGE_EXIT
};

MAKE_ENUM(u8, OptionsTimeAttackStage) {
    OPTIONS_TIME_ATTACK_STAGE_0,
    OPTIONS_TIME_ATTACK_STAGE_1,
    OPTIONS_TIME_ATTACK_STAGE_2,
    OPTIONS_TIME_ATTACK_STAGE_3,
    OPTIONS_TIME_ATTACK_STAGE_4,
    OPTIONS_TIME_ATTACK_STAGE_5,
    OPTIONS_TIME_ATTACK_STAGE_6,
#ifdef REGION_US_BETA
    OPTIONS_TIME_ATTACK_STAGE_6B,
#endif // REGION_US_BETA
    OPTIONS_TIME_ATTACK_STAGE_7,
    OPTIONS_TIME_ATTACK_STAGE_8,
    OPTIONS_TIME_ATTACK_STAGE_9,
    OPTIONS_TIME_ATTACK_STAGE_10,
    OPTIONS_TIME_ATTACK_STAGE_11,
    OPTIONS_TIME_ATTACK_STAGE_12
};

MAKE_ENUM(u8, FileSelectSubMenu) {
    FILE_SELECT_SUB_MENU_MAIN,
    FILE_SELECT_SUB_MENU_FILE,
    FILE_SELECT_SUB_MENU_COPY,
    FILE_SELECT_SUB_MENU_ERASE,
    FILE_SELECT_SUB_MENU_CORRUPTED,
    FILE_SELECT_SUB_MENU_ENTERING_OPTIONS,
    FILE_SELECT_SUB_MENU_LEAVING_OPTIONS,
};

// Offsets in the RAM OAM array for the file select screen

MAKE_ENUM(u8, FileSelectOam) {
    FILE_SELECT_OAM_0,
    FILE_SELECT_OAM_1,
    FILE_SELECT_OAM_2,
    FILE_SELECT_OAM_3,
    FILE_SELECT_OAM_MEDIUM_PANEL,

    FILE_SELECT_OAM_COPY_ARROW,
    FILE_SELECT_OAM_SUB_CURSOR,
    FILE_SELECT_OAM_CURSOR,

    FILE_SELECT_OAM_FILE_A_MARKER,
    FILE_SELECT_OAM_FILE_B_MARKER,
    FILE_SELECT_OAM_FILE_C_MARKER,

    FILE_SELECT_OAM_SMALL_PANEL,

    FILE_SELECT_OAM_FILE_A_LOGO,
    FILE_SELECT_OAM_FILE_B_LOGO,
    FILE_SELECT_OAM_FILE_C_LOGO,

    FILE_SELECT_OAM_COUNT
};

// ----
// Offsets in the RAM OAM array for the options screen

MAKE_ENUM(u8, OptionsOam) {
    OPTIONS_OAM_FUSION_LINK_GBAS,
#ifndef REGION_US_BETA
    OPTIONS_OAM_TIME_ATTACK_LEFT_ARROW,
    OPTIONS_OAM_TIME_ATTACK_RIGHT_ARROW,
#endif // !REGION_US_BETA
    OPTIONS_OAM_LARGE_PANEL,
    OPTIONS_OAM_HUGE_PANEL,

#ifdef REGION_EU
    OPTIONS_OAM_SOUND_TEST_ID,
    OPTIONS_OAM_SOUND_TEST_LEFT_ARROW,
    OPTIONS_OAM_SOUND_TEST_RIGHT_ARROW,
    OPTIONS_OAM_SOUND_TEST_PANEL,
    OPTIONS_OAM_SPEAKER,
    OPTIONS_OAM_CURSOR,
#else // !REGION_EU
    OPTIONS_OAM_CURSOR,
    OPTIONS_OAM_SPEAKER,
    OPTIONS_OAM_SOUND_TEST_ID,
    OPTIONS_OAM_SOUND_TEST_LEFT_ARROW,
    OPTIONS_OAM_SOUND_TEST_RIGHT_ARROW,
    OPTIONS_OAM_SOUND_TEST_PANEL,
#endif // REGION_EU

    OPTIONS_OAM_COUNT
};

// ----
// OAM IDs for the file select menu

MAKE_ENUM(u8, FileSelectOamId) {
    FILE_SELECT_OAM_ID_NONE,
    FILE_SELECT_OAM_ID_SAMUS_HEAD_TURNING_ON,
    FILE_SELECT_OAM_ID_SAMUS_HEAD_IDLE,
    FILE_SELECT_OAM_ID_SAMUS_HEAD_TURNING_OFF,
    FILE_SELECT_OAM_ID_SAMUS_HEAD_OFF,
    FILE_SELECT_OAM_ID_TURN_BACK_HEAD,
    FILE_SELECT_OAM_ID_SAMUS_HEAD_TURNING,

    FILE_SELECT_OAM_ID_SAMUS_SUITLESS_HEAD_TURNING_ON,
    FILE_SELECT_OAM_ID_SAMUS_SUITLESS_HEAD_IDLE,
    FILE_SELECT_OAM_ID_SAMUS_SUITLESS_HEAD_TURNING_OFF,
    FILE_SELECT_OAM_ID_SAMUS_SUITLESS_HEAD_OFF,
    FILE_SELECT_OAM_ID_SAMUS_SUITLESS_TURN_BACK_HEAD,
    FILE_SELECT_OAM_ID_SAMUS_SUITLESS_HEAD_TURNING,

    FILE_SELECT_OAM_ID_FILE_A_MARKER_IDLE,
    FILE_SELECT_OAM_ID_FILE_B_MARKER_IDLE,
    FILE_SELECT_OAM_ID_FILE_C_MARKER_IDLE,
    FILE_SELECT_OAM_ID_FILE_A_MARKER_SELECTED_RED,
    FILE_SELECT_OAM_ID_FILE_B_MARKER_SELECTED_RED,
    FILE_SELECT_OAM_ID_FILE_C_MARKER_SELECTED_RED,
    FILE_SELECT_OAM_ID_FILE_A_MARKER_SELECTED_GREEN,
    FILE_SELECT_OAM_ID_FILE_B_MARKER_SELECTED_GREEN,
    FILE_SELECT_OAM_ID_FILE_C_MARKER_SELECTED_GREEN,

    FILE_SELECT_OAM_ID_CURSOR,
    FILE_SELECT_OAM_ID_CURSOR_IDLE,
    FILE_SELECT_OAM_ID_CURSOR_SELECTED,

    FILE_SELECT_OAM_ID_COPY_ARROW_ONE_DOWN_ACTIVE,
    FILE_SELECT_OAM_ID_COPY_ARROW_ONE_DOWN_INACTIVE,
    FILE_SELECT_OAM_ID_COPY_ARROW_TWO_DOWN_ACTIVE,
    FILE_SELECT_OAM_ID_COPY_ARROW_TWO_DOWN_INACTIVE,
    FILE_SELECT_OAM_ID_COPY_ARROW_ONE_UP_ACTIVE,
    FILE_SELECT_OAM_ID_COPY_ARROW_ONE_UP_INACTIVE,
    FILE_SELECT_OAM_ID_COPY_ARROW_TWO_UP_ACTIVE,
    FILE_SELECT_OAM_ID_COPY_ARROW_TWO_UP_INACTIVE,

    FILE_SELECT_OAM_ID_METROID_LOGO,

    FILE_SELECT_OAM_ID_SMALL_PANEL_OPEN,
    FILE_SELECT_OAM_ID_SMALL_PANEL_CLOSE,
    FILE_SELECT_OAM_ID_LARGE_PANEL_OPEN,
    FILE_SELECT_OAM_ID_LARGE_PANEL_CLOSE,
    FILE_SELECT_OAM_ID_MEDIUM_PANEL_OPEN,
    FILE_SELECT_OAM_ID_MEDIUM_PANEL_CLOSE,

    FILE_SELECT_OAM_ID_COUNT
};

// ----
// OAM IDs for the options menu

MAKE_ENUM(u8, OptionsOamId) {
    OPTIONS_OAM_ID_NONE,
    OPTIONS_OAM_ID_CURSOR,
    OPTIONS_OAM_ID_CURSOR_SELECTED,
    OPTIONS_OAM_ID_GBA_IDLE,
    OPTIONS_OAM_ID_SPEAKERS_IDLE,
    OPTIONS_OAM_ID_GBA_ACTIVE,
    OPTIONS_OAM_ID_SPEAKERS_ACTIVE,
    OPTIONS_OAM_ID_SOUND_TEST_ID,
    OPTIONS_OAM_ID_LEFT_ARROW_MOVING,
    OPTIONS_OAM_ID_LEFT_ARROW_IDLE,
    OPTIONS_OAM_ID_RIGHT_ARROW_MOVING,
    OPTIONS_OAM_ID_RIGHT_ARROW_IDLE,
    OPTIONS_OAM_ID_GBA_LINKING,
    OPTIONS_OAM_ID_GBA_STOPPED,
    OPTIONS_OAM_ID_SMALL_PANEL_OPEN,
    OPTIONS_OAM_ID_SMALL_PANEL_CLOSE,
    OPTIONS_OAM_ID_LARGE_PANEL_OPEN,
    OPTIONS_OAM_ID_LARGE_PANEL_CLOSE,
    OPTIONS_OAM_ID_MEDIUM_PANEL_OPEN,
    OPTIONS_OAM_ID_MEDIUM_PANEL_CLOSE,
    OPTIONS_OAM_ID_HUGE_PANEL_OPEN,
    OPTIONS_OAM_ID_HUGE_PANEL_CLOSE,

    OPTIONS_OAM_ID_COUNT
};

// ----
// Tilemap update requests

MAKE_ENUM(u8, TilemapRequest) {
    TILEMAP_REQUEST_START_GAME_INIT,
    TILEMAP_REQUEST_START_GAME,
    TILEMAP_REQUEST_2,
    TILEMAP_REQUEST_3,
    TILEMAP_REQUEST_4,
    TILEMAP_REQUEST_5,

    TILEMAP_REQUEST_DIFFICULTY_SPAWN_INIT,
    TILEMAP_REQUEST_DIFFICULTY_SPAWN,
    TILEMAP_REQUEST_DIFFICULTY_DESPAWN_INIT,
    TILEMAP_REQUEST_DIFFICULTY_DESPAWN,

    TILEMAP_REQUEST_ERASE_SPAWN_INIT,
    TILEMAP_REQUEST_ERASE_SPAWN,
    TILEMAP_REQUEST_ERASE_DESPAWN_INIT,
    TILEMAP_REQUEST_ERASE_DESPAWN,
    TILEMAP_REQUEST_ERASE_YES_NO_SPAWN_INIT,
    TILEMAP_REQUEST_ERASE_YES_NO_SPAWN,
    TILEMAP_REQUEST_ERASE_YES_NO_DESPAWN_INIT,
    TILEMAP_REQUEST_ERASE_YES_NO_DESPAWN,

    TILEMAP_REQUEST_COPY_SPAWN_INIT,
    TILEMAP_REQUEST_COPY_SPAWN,
    TILEMAP_REQUEST_COPY_DESPAWN_INIT,
    TILEMAP_REQUEST_COPY_DESPAWN,
    TILEMAP_REQUEST_COPY_OVERRIDE_SPAWN_INIT,
    TILEMAP_REQUEST_COPY_OVERRIDE_SPAWN,
    TILEMAP_REQUEST_COPY_OVERRIDE_DESPAWN_INIT,
    TILEMAP_REQUEST_COPY_OVERRIDE_DESPAWN,
    TILEMAP_REQUEST_COPY_DESTINATION_DESPAWN,
    TILEMAP_REQUEST_COPY_DESTINATION_SPAWN,

    TILEMAP_REQUEST_28,
    TILEMAP_REQUEST_29,
    TILEMAP_REQUEST_30,
    TILEMAP_REQUEST_31,
    TILEMAP_REQUEST_32,
    TILEMAP_REQUEST_33,
    TILEMAP_REQUEST_34,
    TILEMAP_REQUEST_35,
    TILEMAP_REQUEST_36,
    TILEMAP_REQUEST_37,
    TILEMAP_REQUEST_38,
    TILEMAP_REQUEST_39,
    TILEMAP_REQUEST_40,
    TILEMAP_REQUEST_41
};

// Cursor poses

MAKE_ENUM(u8, CursorPose) {
    CURSOR_POSE_DEFAULT,
    CURSOR_POSE_MOVING,
    CURSOR_POSE_OPENING_OPTIONS,

    CURSOR_POSE_SELECTING_FILE = 5,
    CURSOR_POSE_DESELECTING_FILE,
    CURSOR_POSE_STARTING_GAME
};

MAKE_ENUM(u8, CursorCopyPose) {
    CURSOR_COPY_POSE_DEFAULT,
    CURSOR_COPY_POSE_MOVING,
    CURSOR_COPY_POSE_SELECTING_FILE,
    CURSOR_COPY_POSE_COPIED
};

MAKE_ENUM(u8, ArrowCopyPose) {
    ARROW_COPY_POSE_DEFAULT,
    ARROW_COPY_POSE_MOVING,
    ARROW_COPY_POSE_COPYING,
    ARROW_COPY_POSE_KILL
};

MAKE_ENUM(u8, CursorErasePose) {
    CURSOR_ERASE_POSE_DEFAULT,
    CURSOR_ERASE_POSE_MOVING,
    CURSOR_ERASE_POSE_SELECTING_FILE,
    CURSOR_ERASE_POSE_ERASED
};

MAKE_ENUM(u8, CursorOptionsPose) {
    CURSOR_OPTIONS_POSE_MOVING,
    CURSOR_OPTIONS_POSE_ENTERING,
    CURSOR_OPTIONS_POSE_SELECTING,
    CURSOR_OPTIONS_POSE_DESELECTING
};

MAKE_ENUM(u16, StereoUpdateFlags) ENUM_FLAG {
    STEREO_UPDATE_FLAGS_IDLE        = 1 << 0,
    STEREO_UPDATE_FLAGS_ACTIVE      = 1 << 1,
    STEREO_UPDATE_FLAGS_SOUND_TEST  = 1 << 2
};

// ----

MAKE_ENUM(u8, FileSelectCursorPosition) {
    FILE_SELECT_CURSOR_POSITION_FILE_A,
    FILE_SELECT_CURSOR_POSITION_FILE_B,
    FILE_SELECT_CURSOR_POSITION_FILE_C,
    FILE_SELECT_CURSOR_POSITION_COPY,
    FILE_SELECT_CURSOR_POSITION_ERASE,
    FILE_SELECT_CURSOR_POSITION_OPTIONS,

    FILE_SELECT_CURSOR_POSITION_COUNT
};

// ----

MAKE_ENUM(u8, OptionId) {
    OPTION_NONE,
    OPTION_STEREO_SELECT,
    OPTION_SOUND_TEST,
    OPTION_TIME_ATTACK,
    OPTION_GALLERY,
    OPTION_FUSION_GALLERY,
    OPTION_FUSION_LINK,
    OPTION_NES_METROID,

    OPTION_COUNT
};

// Sound request ids for FileSelectPlayMenuSound

MAKE_ENUM(u8, MenuSoundRequest) {
    MENU_SOUND_REQUEST_SUB_MENU_CURSOR,
    MENU_SOUND_REQUEST_ACCEPT_CONFIRM_MENU,
    MENU_SOUND_REQUEST_CURSOR,
    MENU_SOUND_REQUEST_FILE_SELECT,
    MENU_SOUND_REQUEST_START_GAME,
    MENU_SOUND_REQUEST_OPEN_SUB_MENU,
    MENU_SOUND_REQUEST_CLOSE_SUB_MENU,
    MENU_SOUND_REQUEST_CLOSE_SUB_MENU2,
    MENU_SOUND_REQUEST_COPY_DELETE,
    MENU_SOUND_REQUEST_COPY_DELETE_MOVING,
    MENU_SOUND_REQUEST_COPY_CONFIRM,
    MENU_SOUND_REQUEST_GAME_OVER_MENU_CURSOR,
    MENU_SOUND_REQUEST_GAME_OVER_START_GAME,

    MENU_SOUND_REQUEST_COUNT
};

#endif /* FILE_SELECT_CONSTANTS_H */
